Data Layer Refactor and Handler Tests
speedrun-website/speedrun-rest pull request #60
Opened 2021-10-23 01:31 UTC by BraydonKains

This is the first PR in the effort to settle #58 

Writing unit tests for the handlers led to a number of challenges related to testing with GORM, which prompted a refactor of the data layer. Instead of exposing the gorm DB object from the `database` package, expose a `UserStore` interface that defines the actions we will use to get User data. This separates data access concerns to the data layer, which subsequently makes the handler testing a lot more sane. 

Wrote the first set of handler tests with a mocked data layer, which tests most common cases for the handlers using `httptest.Recorder` and a test `gin.Context`. These tests can be used as blueprints for contributors adding future handlers.

2021-10-23 06:13 UTC, robotmayo requested changes

2021-10-23 22:39 UTC, robotmayo approved these changes

2021-10-26 23:23 UTC, tendstofortytwo reviewed
The code looks great overall! Left one small nitpick.

2021-10-27 15:00 UTC, FrozenSake reviewed
Some questions/comments, and a concern around returning full user structs. I'm not sure what the best way to validate passwords would be, but creating a struct of it outside the DB feels like not the tea.

2021-10-29 02:14 UTC, TheTedder requested changes

2021-10-30 00:16 UTC, TheTedder approved these changes
Thank you for all the work you've put in on this. The separate between the user store and the db backing it is a good feature.

2021-10-30 00:59 UTC, merged