Change Password Data Format
speedrun-website/speedrun-rest pull request #71
Opened 2021-10-30 03:29 UTC by TheTedder

Salted and hashed passwords are fundamentally byte arrays, not strings, so it makes sense to store them as such. Databases such as postgres have no problem storing raw bytes and this will save us from having to convert it back and forth so much. All salted and hashed passwords returned from bcrypt using GenerateFromPassword are 60 bytes in length, so that was the length I used for the DB field. Make sure to change this in the event that the corresponding bcrypt functionality ever changes or we switch to a different library

2021-10-30 08:02 UTC, zysim requested changes
Getting an error when trying to register a user. `gorm_user_store.go:48 ERROR: could not determine data type of parameter $6 (SQLSTATE 42P18)` getting this, particularly. Not sure if this is a problem with the PR, or if it's a problem with my own DB?

2021-10-30 08:02 UTC, zysim commented on utils/password.go
>  	// convert the bytes to a string and return it
This'd need removing :ok_hand:

2021-10-30 10:18 UTC, TheTedder commented
> Getting an error when trying to register a user. `gorm_user_store.go:48 ERROR: could not determine data type of parameter $6 (SQLSTATE 42P18)` getting this, particularly. Not sure if this is a problem with the PR, or if it's a problem with my own DB?

Ah, that just means gorm isn't smart enough to movie what sql type to use. I know how to fix this though.

2021-10-31 06:45 UTC, zysim commented on utils/password.go
>  	// convert the bytes to a string and return it
Realised that I can just do this myself, so I have lmao

2021-11-02 05:22 UTC, TheTedder reviewed
Alright, it works now.

2021-11-03 09:39 UTC, zysim approved these changes

2021-11-03 09:39 UTC, zysim commented
Yep it sure works now :cowboy_hat_face:

2021-11-03 10:33 UTC, merged